cbvapp/urls.py
from django.urls import path
from cbvapp import views
app_name='cbvapp'
urlpatterns = [

    path('',views.personList.as_view(),name='list'),
    path('<int:pk>',views.persondetail.as_view(),name='detail'),
    path('create/',views.personview.as_view(),name='create'),
    path('update/<int:pk>',views.personupdate.as_view(),name='update'),
    path('delete/<int:pk>',views.persondelete.as_view(),name='delete'),
    path('signup/',views.registration,name='signup'),
    path('signin/',views.userlogin,name='userlogin'),
    path('check/',views.checkuser,name='check'),
    path('search/',views.searchuser,name='search')

]

cbviews/urls.py
from django.contrib import admin
from django.urls import path,include
from cbvapp import views

#To Upload image File
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.myCBV.as_view(),name='index'),
    path('cbvapp/',include('cbvapp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cbvapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
class person(models.Model):
    name = models.CharField(max_length = 250)
    email = models.EmailField()
    age = models.IntegerField()
    profile_pic = models.ImageField(upload_to='person/%Y/%m/%d',null = True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('index')

class bookIssue(models.Model):
    student = models.ForeignKey(person, on_delete= models.CASCADE,related_name='issues')
    book_name = models.CharField(max_length= 200)
    cover = models.FileField(upload_to='book_covers/%Y/%m/%d',null = True)
    author = models.CharField(max_length= 200)
    Issued_on = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.book_name

class signupModel(models.Model):
    user = models.OneToOneField(User,on_delete= models.CASCADE)
    date_of_birth = models.DateField()
    pic = models.ImageField(upload_to='user/%Y/%m/%d')
    registered_on = models.DateTimeField(auto_now_add=True)
    update_on = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.user.username

cbvapp/forms.py
from django import forms
from django.contrib.auth.models import User
from cbvapp.models import signupModel

class userform(forms.ModelForm):
    class Meta():
        model = User
        fields = ('username','email','password')

class profileform(forms.ModelForm):
    class Meta():
        model = signupModel
        fields=('date_of_birth','pic')
        widgets= {
        "date_of_birth":forms.DateInput(attrs={'type':'date'})
        }

cbvapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse
from django.core import serializers
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from cbvapp.models import person
from django.urls import reverse_lazy
from cbvapp.forms import userform, profileform
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.models import User
class myCBV(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['d'] = "data 1"
        context['i'] = 20
        return context

class personList(ListView):
    model = person
    context_object_name = "person"

class persondetail(DetailView):
    model = person

class personview(CreateView):
    model = person
    fields = ('name','email','age','profile_pic')

class personupdate(UpdateView):
    model = person
    fields = ('name','email','age','profile_pic')
    success_url = reverse_lazy('cbvapp:list')

class persondelete(DeleteView):
    model = person
    success_url = reverse_lazy('cbvapp:list')
    template_name ='cbvapp/delete.html'

def registration(request):
    form = userform()
    profile = profileform()
    if request.method == "POST":
        if "signup" in request.POST:
            form = userform(request.POST)
            profile = profileform(request.POST,request.FILES)
            if form.is_valid() and profile.is_valid():
                user = form.save()
                # user.set_password(user.password)
                user.is_staff = True
                user.save()

                profile = profile.save(commit=False)
                profile.user = user
                profile.save()
                return HttpResponseRedirect('/cbvapp/signin/')

    return render(request,'signup.html',{'user':userform,'profile':profileform})

def userlogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('/cbvapp/')
        else:
            return HttpResponse("Sorry You are not registred")
    return render(request,'login.html')

def checkuser(request):
    username = request.GET.get('username')
    check = User.objects.filter(username__iexact=username).exists()
    result = {}
    result['c']=check

    return JsonResponse(result)

def searchuser(request):
    username = request.GET.get('username')
    result = User.objects.filter(username__icontains=username)
    js= serializers.serialize("json", result)
    return HttpResponse(js,content_type='application/json')

cbvapp/templates/cbvapp/delete.html
{% extends "index.html" %}
{% block main %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <h2 class='text-danger'> Are You Sure want to delete <strong>{{person.name}}</strong> </h2>
        <ul>
          <li>After delete you will not see this user again</li>
          <li>It will not recover</li>
        </ul>
        <form method="post">
          {% csrf_token %}
          <input type="submit" name="" class='btn btn-danger' value="Yes I am sure">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

cbvapp/templates/cbvapp/person_detail.html
{% extends "index.html" %}
{% load staticfiles%}
{% block main %}
  <div class="container-fluid">
    <div class="row" style='background:url("{% static "background.jpeg"%}")'>
      <div class="col-md-3">
        <div class="card">
          <div class="card-head">
            <h2 class='card-title'>{{person.name}}</h2>
          </div>
          <div class="card-body">
            <img src="/media/{{person.profile_pic}}" class='card-img' alt="">
          </div>
          <div class="card-footer">
            <button type="button" class='btn btn-warning btn-block' name="button"><a style='text-decoration:none;' href="{% url "cbvapp:update" pk=person.id %}" >Update profile</a></button>
            <button type="button" class='btn btn-danger btn-block' name="button"><a href="{% url "cbvapp:delete" pk=person.id %}" style='text-decoration:none;'>Delete User</a></button>
          </div>
        </div>
      </div>
      <div class="col-md-9 text-center text-dark my-5" style='background:rgba(255,255,255,0.5)'>
        <h1 style='font-family:cursive'>{{person.name}} </h1>
        <h2>{{person.age}} years old</h2>
        <small>{{person.email}}</small>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        {% if not person.students %}
        <h1 class='alert alert-info text-center'>Here are the issued books by {{person.name}}</h1>
        {% else %}
        <h1 class='alert alert-info text-center'>No Book Issues</h1>
        {% endif %}
        <div class="card-columns">
          {% for i in person.issues.all %}
            <div class="card">
                <div class="card-header p-2">
                  <img src="/media/{{i.cover}}" height=200 alt="No Image" class='card-img'>
                </div>
                <div class="card-body text-center">
                  <h2 class='card-title'>{{i.book_name}}</h2>
                  <small>-Issued by {{i.student}}</small>
                  <h5>{{i.author}}</h5>
                  <p>on {{i.Issued_on}}</p>
                </div>
            </div>
          {% endfor %}
        </div>
      </div>

    </div>
  </div>
    {% endblock %}

cbvapp/templates/cbvapp/person_form.html
{% extends "index.html" %}
{% block main %}
{% load bootstrap4 %}
<div class="container-fluid">
  <div class="row bg-dark py-4">
      <div class="col-md-4 bg-light p-4 mx-auto">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" name="create" value="Save">
        </form>
      </div>
  </div>
</div>
{% endblock %}

cbvapp/templates/cbvapp/person_list.html
{% extends "index.html" %}
{% block main %}
  <div class="container">
    <div class="row">
      <div class="col-md-12 py-5">
      <ul class='list-group'>
        {% for i in person %}
          <li class='list-group-item list-group-item-action'> <a href="{{i.id}}"> {{i.id}} &nbsp; {{i.name}} </a> </li>
        {% endfor %}
      </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CBVAPP</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <style media="screen">
      a{
        text-decoration:none;
      }
    </style>
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 px-0">
          <nav class='navbar bg-primary navbar-dark navbar-expand'>
            <a href="{% url "index"%}" class='navbar-brand'>CBV</a>
            <ul class='navbar-nav'>
              <li class='nav-item'>
                <a href="{% url "cbvapp:list" %}" class='nav-link'>Student List</a>
              </li>
              <li class='nav-item'>
                <a href="{% url "admin:index" %}" class='nav-link'>Admin</a>
              </li>
              <li class='nav-item'>
                <a href="{% url "cbvapp:create" %}" class='nav-link'>Add Student</a>
              </li>
              <li class='nav-item'>
                <a href="{% url "cbvapp:signup" %}" class='nav-link'>Sign Up</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    {% block main %}

    {% endblock %}
  </body>
</html>

templates/login.html
{% extends "index.html "%}
{% block main %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 m-5 p-1 mx-auto" style='border:2px solid gray;'>
      <form class=""  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="username" placeholder="Enter Username" class='form-control'>
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Enter Password" class='form-control'>
        </div>
        <input type="submit" name="signup" value="Sign In" class='btn btn-success btn-block '>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/signup.html
{% extends "index.html"%}
{% load bootstrap4 %}
{% block head %}

  <!-- CODE FOR SEARCH USER -->
    <script>
      $(function(){
        $('#id_username').change(function(){
          var username = $(this).val();
          $.ajax({
            url:"{% url "cbvapp:check"%}",
            data:{'username':username},
            success:function(data){
              if(data.c){
                $('.form-text').html("<div class='pl-2 text-danger'><i class='fas fa-times text-danger'></i> A user with this username already exits</div>")
                $('#id_username').css({border:'1px solid red'});
              }
              else{
                $('.form-text').html("<div class='pl-2 text-success'><i class='fas fa-check text-success'></i> Username validated Successfully</div>")
                $('#id_username').css({border:'1px solid green'})

              }
            }
          });
        });
  // CODE FOR CHECK USER
        $('#cont').keypress(function(){
          var a = $(this).val();
          $.ajax({
            url:'{% url "cbvapp:search"%}',
            data:{'username':a},
            success:function(data){
              var a = '';
              for(i in data){
                a += "<tr>";
                a += "<td>"+data[i].pk+"</td>";
                a += "<td>"+data[i].fields.username+"</td>";
                a += "<td>"+data[i].fields.email+"</td>";
                a += "</tr>";

              }
              $('.tb').html(a);
            }
          })

        });
      });
    </script>
{% endblock %}
{% block main %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <h2 class='text-center'>Search Users</h2>
        <input type="text" name="" id='cont' placeholder="Search by username..." class='my-3 form-control'>
        <table class='table table-striped'>
          <thead class='bg-dark text-light'>
            <tr>
              <th>ID</th>
              <th>Username</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody class='tb'>

          </tbody>
        </table>
      </div>

      <div class="col-md-6 p-3 mx-auto" style='border:2px solid gray;'>
        <form class=""  method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form user %}
          {% bootstrap_form profile %}
          <input type="submit" name="signup" value="Sign Up" class='btn btn-primary btn-block '>
        </form>
      </div>
    </div>
  </div>
{% endblock %}